.travis.yml, CONTRIBUTING.md, README.md, package.json
Commit workflow, contribution guide and readme badges are also included.
BREAKING CHANGE: Not really, just want to start on v1.0
=> ci(release): Set up semantic-release

README.md
Ran through the setup process and found a few rough edges, so figured I'd clean them up as I went.
=> docs(setup): Add git instructions, use diff notation for npm scripts

config/webpack/webpack.config.js, package.json
Add ModuleConcatenationPlugin to production builds
=> feat(webpack): Upgrade to webpack 3

README.md, config/builds.js, config/webpack/webpack.config.js, scripts/start.js
- Add live reload
- Add error overlay 
- Show only error logs 
- Support custom hosts 
- Make port configurable 
- Add historyApiFallback
=> feat(webpack-dev-server): Improve dev experience with webpack dev server

package.json
Please re-approve, I couldn't figure out how to change the title >_<
=> fix(dependencies): remove seek-style-guide

package.json
Updating extract-text-webpack-plugin to 3.0.0 to fix CSS resolving order issues
https://github.com/webpack/webpack/issues/215
=> fix(webpack): Update extract-text-webpack-plugin

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md
Since this repo now has multiple active consumers, it seems like a good time to raise the level of transparency for incoming changes. Not only will this help consumers and contributors keep up in an asynchronous way, but it will also provide a more structured way for active contributors to elaborate on their ideas, gain consensus and get actionable feedback.
=> chore(GitHub): Add RFC workflow and release notes documentation

.gitignore, config/babel/babelConfig.js, package.json
Add [babel-plugin-flow-react-proptypes](https://www.npmjs.com/package/babel-plugin-flow-react-proptypes) to development builds.
This is a useful feature for teams using [flow](https://flow.org/) and should not impact teams who are not.  
EXAMPLE USAGE:
See [babel-plugin-flow-react-proptypes](https://www.npmjs.com/package/babel-plugin-flow-react-proptypes)
=> feat(babel): Add flow to prop types babel plugin

config/webpack/webpack.config.js, config/webpack/webpack.config.ssr.js
Ensure polyfills are loaded before `react-hot-loader/patch` in development environment.
=> fix(polyfills): Ensure polyfills are loaded first

config/builds.ssr.js
PR #141 was missing support for the initialPath configuration option for SSR
=> fix(initialPath): Add 'initialPath' support for SSR

config/jest/jestConfig.js, jest.config.js
Preemptive defence against https://github.com/facebook/jest/issues/6766.
=> fix(jest): Add testURL Jest config

README.md
This PR adds documentation for SSR, making it a supported feature of sku.
=> feat(docs): Added SSR documentation

README.md
Some documentation about how to statically render multiple files.
=> docs(README): Static rendering multiple pages

.pullapprove.yml
Upgrade to PullApprove v3 and migrate to centralised config
=> chore(PullApprove): Migrate to v3

README.md, context/clientEntries.js, context/defaultSkuConfig.js, context/index.js, context/validateConfig.js, docs/migration-guides/v7.0.0.md, docs/static-rendering.md, template/sku.config.js, test/test-cases/custom-src-paths/sku.config.js, test/test-cases/library-build/app/sku.config.js, test/test-cases/typescript-css-modules/app/sku.config.js
BREAKING CHANGE: `entry` config object has been removed in favour of specific entry values
=> refactor: Flatten entry config

lib/product.test.js, test/test-cases/multiple-entries/__snapshots__/multiple-entries.test.js.snap, test/test-cases/multiple-entries/multiple-entries.test.js, test/test-cases/multiple-entries/sku.config.js
Small fix due to some tests failing locally.
Use `lodash` sort function for readability, and ensure sort is deterministic.
Use seperate port to ensure no port conflicts if test servers are not successfully shut down before next test starts.
=> test: Unique ports and deterministic sort order for tests

config/webpack/utils/loaders.js, config/webpack/webpack.config.js, config/webpack/webpack.config.ssr.js
Also, refactor CSS loader options to be more consistent
=> fix(webpack): Remove css-modules-typescript-loader on compile packages

test/manual.js
Finding myself using the test cases quite often and this should help iterate on new features. 
I'm aware this is not an ideal fix but it at least gets the manual script working again. I think an ideal solution would be a larger refactor of the test directory structure.
=> test(manual): Fix manual test script

entry/makeExtractor.js, package.json, test/test-cases/braid-design-system/__snapshots__/braid-design-system.test.js.snap, test/test-cases/custom-src-paths/__snapshots__/custom-src-paths.test.js.snap, test/test-cases/multiple-routes/__snapshots__/multiple-routes.test.js.snap, test/test-cases/public-path/__snapshots__/public-path.test.js.snap, test/test-cases/react-css-modules/__snapshots__/react-css-modules.test.js.snap, test/test-cases/seek-asia-style-guide/__snapshots__/seek-asia-style-guide.test.js.snap, test/test-cases/seek-style-guide/__snapshots__/seek-style-guide.test.js.snap, test/test-cases/source-maps/__snapshots__/source-maps.test.js.snap, test/test-cases/ssr-hello-world/__snapshots__/ssr-hello-world.test.js.snap, test/test-cases/typescript-css-modules/__snapshots__/typescript-css-modules.test.js.snap, yarn.lock
Also, move react and loadable/component to peer dependencies
=> fix: Update loadable to fix crossorigin issues

context/configSchema.js, docs/_navbar.md, docs/docs/multi-site.md, docs/migration-guides/_sidebar.md, docs/migration-guides/v8.0.0.md
Also, make small config schema change.
=> docs: Add sku 8 migration guide

package.json
This PR allows Matt to play with his new toy.
=> chore: Setup notion toolchain

renovate.json
Decided that we should actually `enable` the new package rules in order to see them work 🤦‍♂️
=> chore(renovate): Enable new package rules

package.json, yarn.lock
Seems to fix our test issues in CI.
=> chore(deps): Update Puppeteer to ‘next’ tag

entry/makeExtractor.js
Potentially useful for forcing chunks to be loaded before the render is performed.
Probably worth not documenting it yet as an experimental?
@mattsjones, let me know if you want me to add stuff around it.
=> feat(skuParams): Return extractor instance along with the params

lib/openBrowser/index.js, lib/openBrowser/openChrome.applescript, package.json, scripts/start-ssr.js, scripts/start.js, yarn.lock
This will allow `start` & `start-ssr` to reuse an existing chrome tab if the following conditions are met:
- OS is macOS
- The user's default browser is chrome
- There is an existing tab open with the exact same URL
If any of the above is not true, a new tab will be created in the user's default browser.
=> feat(start): Reuse Chrome tab if possible

package.json, template/src/App/App.tsx, template/src/App/NextSteps.tsx, test/test-cases/braid-design-system/__snapshots__/braid-design-system.test.js.snap, test/test-cases/braid-design-system/app/sku.config.js, test/test-cases/braid-design-system/app/src/App.js, test/test-cases/braid-design-system/braid-design-system.test.js, yarn.lock
Also, add `sku build` test for `braid-design-system` test case.
=> fix(init): Use Braid reset in init template

config/storybook/storybookWebpackConfig.js, config/webpack/webpack.config.js, config/webpack/webpack.config.ssr.js, scripts/start-ssr.js, scripts/start.js
Add hot reloading to the storybook setup to better support development iteration cycle while working on components.
=> fix(storybook): Support hot reloading

bin/sku.js, lib/validatePeersDeps.js, package.json, scripts/validate.js, yarn.lock
Note: we have chosen to not break the build for now but will consider it in future.
Example of printed warnings.
=> feat: Detect peer dependency issues

package.json, renovate.json, yarn.lock
Upgrading to the latest playroom to take advantage of a heap of new features.
- Configurable themes & widths as user preference
- Configurable themes & widths in share url
- Add ability to dock editor to the right
- Render only visible frames and lazy load others on scroll
- Improve response time when typing in the code editor
- Resolve code truncation issue when popping editor out
=> fix(deps): Upgrade playroom

config/webpack/plugins/createHtmlRenderPlugin.js
This change should increase build speed by roughly 200-300ms per route/site/environment.
=> perf(build): Increase render speed of routes

config/webpack/plugins/createHtmlRenderPlugin.js, config/webpack/webpack.config.js, package.json, yarn.lock
=> fix(build): Rollback last patch due to out of memory errors

.changeset/thick-grapes-repair.md, scripts/build.js
This is a massive hack that I am not proud of.
=> Allow force exiting build script

.changeset/eight-phones-worry.md, config/playroom/makePlayroomConfig.js, context/configSchema.js, context/defaultSkuConfig.js, context/index.js, docs/docs/configuration.md, docs/docs/playroom.md, package.json, yarn.lock
=> Playroom: Update to v0.22.0, add 'playroomScope' option

lib/hosts.js
Not worth a new version, so LMK if you'd still like a changeset.
=> Fix setup-hosts typo

.changeset/stupid-walls-taste.md, context/configSchema.js, docs/docs/configuration.md, docs/docs/multi-language.md, lib/language-utils.js, test/test-cases/translations/app/sku.config.js
See [Route specific languages in multi-language.md](https://github.com/seek-oss/sku/blob/disable-render-with-language/docs/docs/multi-language.md#route-specific-languages) for details
=> Add the ability to limit languages to render by route

.changeset/new-bags-trade.md, config/webpack/webpack.config.js, config/webpack/webpack.config.ssr.js, context/configSchema.js, context/defaultSkuConfig.js, context/index.js, docs/docs/configuration.md, test/test-cases/braid-design-system/__snapshots__/braid-design-system.test.js.snap, test/test-cases/custom-src-paths/__snapshots__/custom-src-paths.test.js.snap, test/test-cases/multiple-routes/__snapshots__/multiple-routes.test.js.snap, test/test-cases/multiple-routes/app/sku.config.js, test/test-cases/public-path/__snapshots__/public-path.test.js.snap, test/test-cases/react-css-modules/__snapshots__/react-css-modules.test.js.snap, test/test-cases/seek-style-guide/__snapshots__/seek-style-guide.test.js.snap, test/test-cases/sku-with-https/__snapshots__/sku-with-https.test.js.snap, test/test-cases/source-maps/__snapshots__/source-maps.test.js.snap, test/test-cases/ssr-hello-world/__snapshots__/ssr-hello-world.test.js.snap, test/test-cases/translations/__snapshots__/translations.test.js.snap, test/test-cases/typescript-css-modules/__snapshots__/typescript-css-modules.test.js.snap
=> Add skipPackageCompatibilityCompilation option

.changeset/stupid-cars-push.md, config/webpack/utils/loaders.js, package.json, yarn.lock
Fixes the logging issues that were coming up with new sku.
We don't need to have svgo installed anymore, so it can just be a subdependency for svgo-loader.
=> Fix svgo plugin config

.changeset/config.json, .github/workflows/release.yml
Mainly to fix the `Release - undefined` notification in slack 😄
=> Upgrade changesets action

.changeset/large-wombats-wonder.md, config/babel/babelConfig.js, test/test-cases/braid-design-system/__snapshots__/braid-design-system.test.js.snap, test/test-cases/custom-src-paths/__snapshots__/custom-src-paths.test.js.snap, test/test-cases/multiple-routes/__snapshots__/multiple-routes.test.js.snap, test/test-cases/sku-with-https/__snapshots__/sku-with-https.test.js.snap, test/test-cases/typescript-css-modules/__snapshots__/typescript-css-modules.test.js.snap
This is technically rolling back a small change from sku 11.
=> Run babel transform-runtime in development

.changeset/khaki-icons-crash.md, .changeset/shiny-bikes-cough.md, config/webpack/plugins/sku-webpack-plugin/index.js, package.json, test/test-cases/braid-design-system/__snapshots__/braid-design-system.test.js.snap, test/test-cases/braid-design-system/braid-design-system.test.js, test/test-cases/sku-webpack-plugin/__snapshots__/sku-webpack-plugin.test.js.snap, test/test-cases/sku-webpack-plugin/sku-webpack-plugin.test.js, yarn.lock
Also run the `@vanilla-extract/webpack-plugin` in node builds to ensure class name consistency
=> Update vanilla webpack plugin

docs/docs/server-rendering.md
This is no longer supported since v11
=> Remove reference to test-ssr command

docs/docs/multi-language.md
Make the code look similar to the [custom locale](https://seek-oss.github.io/sku/#/./docs/multi-language?id=custom-locale) example
=> Slightly better code for pseudo-localization

docs/yarn.lock
Relocking the docs yarn lock so I can close some more dependabot alerts.
=> Relock docs yarn.lock

.changeset/spicy-snails-know.md, package.json, yarn.lock
In retrospect I should probably have actually checked this
=> Rollback typescript version

docs/docs/styling.md
Documentation link to vanilla-extract was broken so just fixing it here
=> fix broken link to vanilla-extract docs

.changeset/rich-carrots-pull.md, .eslintignore, .eslintrc, .gitignore, .vscode/extensions.json, .vscode/settings.json, jest.config.js, package.json, test/test-cases/braid-design-system/__snapshots__/braid-design-system.test.js.snap, test/test-cases/lint-rules/__snapshots__/import-order.test.js.snap, test/test-cases/lint-rules/app/.eslintignore, test/test-cases/lint-rules/app/.gitignore, test/test-cases/lint-rules/app/.prettierignore, test/test-cases/lint-rules/app/sku.config.js, test/test-cases/lint-rules/import-order.test.js, test/test-cases/multiple-routes/__snapshots__/multiple-routes.test.js.snap, test/test-cases/translations/__snapshots__/translations.test.js.snap, yarn.lock
See commit history for details
=> Bump `eslint-config-seek` & misc improvements

yarn.lock
`yarn upgrade --scope @babel && yarn upgrade --pattern "jest" && npx yarn-deduplicate`
=> Update babel and jest deps in `yarn.lock`

test/test-cases/braid-design-system/__snapshots__/braid-design-system.test.js.snap, test/test-cases/lint-rules/__snapshots__/import-order.test.js.snap, test/test-cases/multiple-routes/__snapshots__/multiple-routes.test.js.snap, test/test-cases/sku-webpack-plugin/__snapshots__/sku-webpack-plugin.test.js.snap, test/test-cases/translations/__snapshots__/translations.test.js.snap, yarn.lock
Ran `yarn upgrade --pattern "webpack|babel|@vocab|css|@vanilla-extract|eslint|postcss" && npx yarn-deduplicate`
=> Refresh a bunch of deps in `yarn.lock`

.husky/pre-commit, package.json, pnpm-lock.yaml
Migrated using https://github.com/typicode/husky-4-to-8
=> Upgrade to Husky 8

fixtures/storybook-config/.eslintignore, fixtures/storybook-config/.gitignore, fixtures/storybook-config/.prettierignore, fixtures/storybook-config/package.json, fixtures/storybook-config/sku.config.ts, fixtures/storybook-config/src/StorybookDecorator.tsx, fixtures/storybook-config/src/TestComponent.stories.tsx, fixtures/storybook-config/src/TestComponent.tsx, pnpm-lock.yaml, tests/package.json, tests/react-css-modules.test.js, tests/storybook-config.test.js
Will be adding a few quality of life storybook config options alongside the upcoming storybook v7 release. This fixture will be used to test those config options.
Note: The fixture intentionally doesn't have any entrypoints since it should only be used for testing storybook.
=> test: Add storybook config fixture

packages/sku/lib/configure.js
=> Remove stray `console.log`

.github/workflows/validate.yml
Because I don't want to wait for the same thing to run twice:
=> Skip duplicate workflow runs

.github/workflows/validate.yml
https://github.com/seek-oss/braid-design-system/pull/1310
=> Sync workflow with Braid

.changeset/eslint-config.md, fixtures/storybook-config/.storybook/preview.tsx, fixtures/translations/package.json, fixtures/translations/sku-ssr.config.ts, fixtures/translations/sku.config.ts, fixtures/typescript-css-modules/src/server.tsx, package.json, packages/sku/config/eslint/eslintConfig.js, packages/sku/package.json, pnpm-lock.yaml, tests/__snapshots__/translations-ssr.test.ts.snap, tests/__snapshots__/translations.test.ts.snap, tsconfig.json
Also ran `pnpm dedupe`, hence the large lockfile update
=> Bump eslint-config-seek

.changeset/typescript-eslint.md
It's now included in `eslint-config-seek`
=> Remove mention of workaround

package.json, pnpm-lock.yaml
Didn't want these lockfile changes to be in an upcoming PR, so I'm bumping pnpm separately.
=> Bump `pnpm` to `v8.6.12`

.changeset/thirty-pots-invite.md, packages/sku/package.json, pnpm-lock.yaml
[Skuba just went to 5.2](https://github.com/seek-oss/skuba/releases/tag/v7.2.0), we might as well try to keep up.
=> Update TypeScript to 5.2

CONTRIBUTING.md, packages/sku/README.md
A long overdue update. Happy to iterate on this re: open source/outside contributors, but it should be good enough for now.
=> Update contribution guide, small readme format change

package.json
So we can more confidently move to v9.
=> Update pnpm to latest 8.x version

.github/workflows/release.yml, .github/workflows/snapshot.yml, .github/workflows/validate.yml
To fix [these warnings](https://github.com/seek-oss/sku/actions/runs/9264271233).
=> Update setup node action

.changeset/stupid-seals-think.md, docs/docs/configuration.md, docs/docs/extra-features.md, fixtures/braid-design-system/sku.config.js, fixtures/library-build/sku.config.js, fixtures/library-file/sku.config.js, packages/sku/config/webpack/cache.js, packages/sku/context/configSchema.js, packages/sku/context/defaultSkuConfig.js, packages/sku/context/index.js, packages/sku/sku-types.d.ts
=> sku v13: remove `persistentCache` config option

packages/sku/lib/configure.js, packages/sku/lib/packageManager.js, packages/sku/lib/parseArgs.js, packages/sku/lib/resolveEnvironment.js, packages/sku/lib/runBin.js, packages/sku/lib/runPrettier.js, packages/sku/lib/runWebpack.js, packages/sku/lib/suggestScript.js, packages/sku/package.json, pnpm-lock.yaml
Added `@ts-check` annotations to a few files where it either required no other changes or minimal type tweaks in other files.
=> Add `@ts-check` to some more files

pnpm-lock.yaml, tests/lint-format.test.js, tests/package.json, tests/storybook-config.test.js
- Replace `node-fetch` with native `fetch`
- Replace `strip-ansi` with native [`stripVTControlCharacters`](https://nodejs.org/api/util.html#utilstripvtcontrolcharactersstr)
=> Replace some dev deps with native alternatives

.changeset/olive-cups-kiss.md, docs/docs/cli.md, docs/docs/getting-started.md, packages/sku/README.md, packages/sku/lib/program/commands/init/init.command.js
Uplifting the CLI docs to reflect the new interface.
Fixed a typo in the changeset and added more information regarding a flag change.
=> Uplift cli docs

CONTRIBUTING.md
Small update in the contribution guide mentioning plop.
=> Uplift contribution docs mentioning plop for boilerplate generation

packages/sku/lib/program/commands/index.mjs, packages/sku/lib/program/commands/test/test.action.mjs, packages/sku/lib/program/commands/test/test.command.mjs, plop/generators/add-sku-command/index.mjs
Turning the test command file into MJS.
Also updated the name of the generator for plop.
=> Test command mjs

packages/sku/lib/program/commands/build/build.action.mjs, packages/sku/lib/program/commands/build/build.command.mjs, packages/sku/lib/program/commands/index.mjs
=>  Migrate `build` command and action to mjs

packages/sku/lib/eslintMigration.mjs, packages/sku/lib/eslintMigration.test.mjs, packages/sku/lib/exists.mjs, packages/sku/lib/getSiteForHost.mjs, packages/sku/lib/gracefulSpawn.mjs, packages/sku/lib/hosts.mjs, packages/sku/lib/install.mjs
Note that file extensions in dependent files have intentionally not been updated. They will be addressed in the future.
=> Migrate more files to ESM

tests/assertion-removal.test.ts, tests/braid-design-system.test.js, tests/configure.test.ts, tests/custom-src-paths.test.ts, tests/jest-test.test.ts, tests/library-build.test.js, tests/library-file.test.js, tests/lint-format.test.js, tests/multiple-routes.test.js, tests/package.json, tests/public-path.test.js, tests/sku-test.test.ts, tests/sku-webpack-plugin.test.js, tests/sku-with-https.test.js, tests/source-maps.test.js, tests/ssr-hello-world.test.js, tests/storybook-config.test.js, tests/styling.test.ts, tests/suspense.test.ts, tests/translations-ssr.test.ts, tests/translations.test.ts, tests/typescript-css-modules.test.ts
Turned all `tests` into esm. 
Requires `test-utils` to be esm as well.
=> Change `tests` into esm

packages/sku/package.json, packages/sku/src/lib/preCommit.ts, pnpm-lock.yaml
Bump the seek-config-eslint package
=> Bump the seek-config-eslint package

.changeset/brown-teachers-teach.md, pnpm-lock.yaml
Add changeset outlining the update to ESM and notifying users to update files.
=> add changeset for esm change

packages/sku/CHANGELOG.md, packages/sku/package.json, packages/sku/src/lib/packageManager.ts, packages/sku/src/lib/program/commands/init/init.action.ts
I _think_ this should allows `version-14` to be merged cleanly into `master`.
=> Port pnpm v10 fix to v14

.changeset/stupid-maps-fry.md
Need to merge this to try figure out what happened in #1163.
=> Add test changeset

docs/docs/_sidebar.md, docs/docs/using-vite.md, docs/docs/vite-support.md
Add docs for `vite`.
Docs are a slight re-write of the changeset.
=> docs: vite experimental docs

docs/docs/vite-support.md, fixtures/vite-test-app/sku.config.ts, packages/sku/src/context/createSkuContext.ts, packages/sku/src/context/defaultSkuConfig.ts, packages/sku/src/types/types.ts
Change the `bundler` key to `__UNSAFE_EXPERIMENTAL__bundler` to reflect its experimental and unsafe nature.
=> Change bundler key to one that reflects its experimental nature

packages/sku/package.json, pnpm-lock.yaml
Fast follow to https://github.com/seek-oss/sku/pull/1241#discussion_r2083662218
=> pin vocab version

docs/docs/cli.md
My spellchecker doesn't work inside backticks 😭.
=> Fix CLI docs typo

.changeset/lazy-cups-speak.md, packages/sku/src/program/commands/init/init.action.ts, pnpm-lock.yaml
Adds deprecation warnings to `sku init` command directing users to the new `@sku-lib/create` package.
=> Add deprecation warnings to `sku init`

docs/docs/vite.md
Adding a few updates to the docs
=> adding note to install the sku vite package
